### ISSUE TITLE
Plugins not being loaded

### ISSUE THREAD

**Issue by marciol** [tacnoman/dephpugger#20]
The `dephpugger debug` does not work due some problem with autoload.

I observed that `get_declared_classes` function at line https://github.com/tacnoman/dephpugger/blob/master/src/Dephpug/PluginReflection.php#L38 don't retrieve classes defined on `src/Dephpug/Command` and `src/Dephpug/Parser` directory.

Seems some problem with autoload.

I make all working with the follow change at `bin/dephpugger`:

```php
$command_dir = __DIR__ .
    DIRECTORY_SEPARATOR . '..' .
    DIRECTORY_SEPARATOR . 'src' .
    DIRECTORY_SEPARATOR . 'Dephpug' .
    DIRECTORY_SEPARATOR . 'Command';

$command_files = glob($command_dir . DIRECTORY_SEPARATOR . '' . '*.php');

foreach ($command_files as $filename) {
    require_once $filename;
}

$parser_msgs_dir = __DIR__ .
    DIRECTORY_SEPARATOR . '..' .
    DIRECTORY_SEPARATOR . 'src' .
    DIRECTORY_SEPARATOR . 'Dephpug' .
    DIRECTORY_SEPARATOR . 'Parser';

$parser_msgs_files = glob($parser_msgs_dir . DIRECTORY_SEPARATOR . '' . '*.php');

foreach ($parser_msgs_files as $filename) {
    require_once $filename;
}
```

Given that I'm not a PHP expert, maybe a better solution exists.

**Comment by ricardotulio** [comment]
My bad @marciol, it was caused because my PR #18. In my opinion, the PluginReflection must be abandoned and a plugin provider must be implemented and provide this plugin explicit.

PluginReflection class hide some side effects. In the same way that my previous refactoring, the code are being responsible for manage these class dependencies, and for me, its not a responsibility of this project, although composer can do this in better way. 

My suggestion: add this files fixed on composer.json and then refact this PluginReflection class, in two separed PRs.

What you mean @marciol and @tacnoman?

**Comment by tacnoman** [comment]
Hello @marciol 
I fixed this bug in last version.
You must only upgrade your dephpugger to version `1.2.2`.

Thanks to report.
